<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Bharath" failures="1" tests="6" name="Test" time="0.072" errors="0" timestamp="2025-01-15T09:04:46 IST">
  <testcase classname="com.framework.testngConcepts.TestNGTests" name="TestCase3" time="0.006"/>
  <testcase classname="com.framework.testngConcepts.TestNGTests" name="TestCase3" time="0.001"/>
  <testcase classname="com.framework.testngConcepts.TestNGTests" name="TestCase4" time="0.001"/>
  <testcase classname="com.framework.testngConcepts.TestNGTests" name="TestCase1" time="0.003">
    <skipped/>
  </testcase> <!-- TestCase1 -->
  <testcase classname="com.framework.testngConcepts.TestNGTests" name="TestCase1" time="0.001">
    <skipped/>
  </testcase> <!-- TestCase1 -->
  <testcase classname="com.framework.testngConcepts.TestNGTests" name="TestCase1" time="0.001">
    <failure type="java.lang.AssertionError" message="Test Case 1 Failed">
      <![CDATA[java.lang.AssertionError: Test Case 1 Failed
at com.framework.testngConcepts.TestNGTests.TestCase1(TestNGTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TestCase1 -->
  <testcase classname="com.framework.testngConcepts.TestNGTests" name="TestCase2" time="0.0">
    <ignored/>
  </testcase> <!-- TestCase2 -->
</testsuite> <!-- Test -->
